version: '2'

volumes:
  data:

services:
  mongo:
    image: mongo:latest
    volumes:
      - data:/data
  node:
    build: .
    command: python -m nxtools.hooks.app
    volumes:
      - ./dist:/opt/dist
      - ./conf:/opt/conf
      - data:/opt/data
    links:
      - mongo
    environment:
      - NXTOOLS_HOOKS_CONF=/opt/conf/nuxeo-tools-hooks.ini
      - NXTOOLS_HOOKS_LOGGING_CONFIG_FILE=/opt/conf/log.ini
      - NXTOOLS_HOOKS_DATABASE_CONNECTION_URL=mongodb://mongo/nxtools-hooks
  proxy:
    image: nginx:stable
    links:
    - node:captainhook-node
    volumes:
      - ./docker/nginx-proxy/custom.conf:/etc/nginx/conf.d/10-custom.conf
