version: '2'

volumes:
  data:

services:
  mongo:
    image: mongo:latest
    volumes:
      - data:/data
  api:
    build: ./docker
    volumes:
      - ./docker/entrypoint.sh:/entrypoint.sh
      - ./nuxeo-tools-hooks/nxtools/hooks/doc/vhost.conf:/etc/apache2/sites-enabled/vhost.conf
      - ./requirements.txt:/opt/requirements.txt
      - ./dist:/opt/dist
      - ./conf:/opt/conf
      - data:/opt/data
    links:
      - mongo
    environment:
      - NXTOOLS_HOOKS_CONF=/opt/conf/nuxeo-tools-hooks.ini
      - NXTOOLS_HOOKS_DATABASE_CONNECTION_URL=mongodb://mongo/nxtools-hooks